# Docs: https://github.com/Azure/webapps-deploy
# Node.js App Deployment Workflow

name: Build and deploy Node.js app to Azure Web App - realestateappp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd api
          npm install

      # Install frontend dependencies and build
      - name: Install frontend dependencies and build
        run: |
          cd client
          npm install
          npm run build

      # Move frontend build into backend (for deployment as one package)
      - name: Move frontend build into backend
        run: |
          rm -rf api/client
          mv client/build api/client

      # Zip the backend (with frontend build inside)
      - name: Zip deployment package
        run: |
          cd api
          zip -r ../release.zip .

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.__clientidsecretname__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'realestateappp'
          slot-name: 'Production'
          package: .
